{
 "title": "Lotus Node Health",
 "description": "Dashboard to track Filecoin Lotus node stats.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Filecoin Network Peers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_peer_count", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Network Height",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_chain_node_worker_height", "legendFormat": "worker-{{ pod }}" }
   ]
  },
  {
   "title": "error method=\"Filecoin.MpoolPushMessage\"",
   "type": "bargauge",
   "description": " Counter for total dropped RPCs",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_rpc_response_error", "legendFormat": "{{ service }}" }
   ]
  },
  {
   "title": "RPC received",
   "type": "bargauge",
   "description": " Counter for total received RPCs",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_pubsub_recv_rpc", "legendFormat": "{{ service }} received" }
   ]
  },
  {
   "title": "RPC counts(sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(lotus_pubsub_rejected)", "legendFormat": "total rejected messages" },
    { "expr": "sum(lotus_pubsub_drop_rpc)", "legendFormat": "total dropped RPCs" },
    { "expr": "sum(lotus_pubsub_send_rpc)", "legendFormat": "total sent RPCs" }
   ]
  },
  {
   "title": "Duration for Block Validation in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lotus_block_validation_ms_count",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Lotus memory allocated(MB)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_process_sys_memory_alloc / 1048576",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Node Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "(lotus_info)", "legendFormat": "{{ pod }}- {{ version }}" }
   ]
  }
 ]
}