{
 "title": "Lotus Node Health",
 "description": "Dashboard to track Filecoin Lotus node stats.",
 "tags": [ "lotus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Node Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "lotus_info" }
   ]
  },
  {
   "title": "Filecoin Network Peers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_peer_count", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Network Height",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "lotus_chain_node_worker_height", "legendFormat": "worker-{{ pod }}" }
   ]
  },
  {
   "title": "Duration for Block Validation in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_block_validation_ms_sum[5m])/rate(lotus_block_validation_ms_count[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Lotus memory allocated(MB)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_process_sys_memory_alloc / 1048576",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}